"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ensureAnonymousSession } from "@/lib/supabase/anonymous";

type Player = { displayName: string | null };
type RecentGame = { gameId: string; opponent: string; updatedAt: number };
type EntryState = { phase: "INITIALIZING_SESSION" } | { phase: "LOADING_PLAYER" } | { phase: "READY_UNNAMED" } | { phase: "READY_NAMED"; displayName: string } | { phase: "NAMING"; continuation: "CREATE" } | { phase: "CREATING_GAME" } | { phase: "SESSION_ERROR" };
async function request(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, credentials: "same-origin", headers: { "content-type": "application/json", ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.code ?? "REQUEST_FAILED"); return body; }

export function GameLobby() {
  const router = useRouter(); const [state, setState] = useState<EntryState>({ phase: "INITIALIZING_SESSION" }); const [name, setName] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [error, setError] = useState(""); const [recent, setRecent] = useState<RecentGame[]>([]);
  useEffect(() => { let active = true; try { setRecent(JSON.parse(localStorage.getItem("gin-rummy:recent-games") ?? "[]") as RecentGame[]); } catch { /* optional local history */ } void (async () => { try { await ensureAnonymousSession(); if (!active) return; setState({ phase: "LOADING_PLAYER" }); const body = await request("/api/me") as { player?: Player }; if (!active || !body.player) return; setState(body.player.displayName ? { phase: "READY_NAMED", displayName: body.player.displayName } : { phase: "READY_UNNAMED" }); } catch { if (active) setState({ phase: "SESSION_ERROR" }); } })(); return () => { active = false; }; }, []);
  async function createForNamedPlayer(displayName: string) { setState({ phase: "CREATING_GAME" }); try { const created = await request("/api/games", { method: "POST" }) as { inviteToken: string; view: { gameId: string } }; sessionStorage.setItem(`gin-rummy:invite:${created.view.gameId}`, created.inviteToken); router.push(`/game/${created.view.gameId}`); } catch (cause) { setError(message(cause)); setState({ phase: "READY_NAMED", displayName }); } }
  async function createGame() { setError(""); if (state.phase === "READY_UNNAMED") return setState({ phase: "NAMING", continuation: "CREATE" }); if (state.phase === "READY_NAMED") await createForNamedPlayer(state.displayName); }
  async function saveName(event: FormEvent) { event.preventDefault(); if (state.phase !== "NAMING") return; setError(""); try { const body = await request("/api/profile", { method: "POST", body: JSON.stringify({ displayName: name }) }) as { displayName: string }; await createForNamedPlayer(body.displayName); } catch (cause) { setError(message(cause)); } }
  function openInvite(event: FormEvent) { event.preventDefault(); setError(""); const token = inviteTokenFromLink(inviteLink); if (!token) return setError("Paste a complete invitation link or its invitation code."); router.push(`/join/${token}`); }
  if (state.phase === "INITIALIZING_SESSION" || state.phase === "LOADING_PLAYER") return <main className="game-shell"><p className="simple-panel" role="status">Preparing your table…</p></main>;
  if (state.phase === "SESSION_ERROR") return <main className="game-shell"><section className="simple-panel"><p role="alert">We couldn’t prepare your player. Try again.</p><button className="action-button primary" onClick={() => window.location.reload()}>Retry</button></section></main>;
  if (state.phase === "NAMING") return <main className="game-shell landing-shell"><section className="name-panel" aria-labelledby="name-title"><p className="eyebrow">A private game for two</p><h1 id="name-title">What should we call you?</h1><p>Your name helps your friend recognize you. We’ll remember it on this device for future tables.</p><form onSubmit={saveName}><label>Your name<input autoFocus value={name} maxLength={40} onChange={(event) => setName(event.target.value)} /></label><button className="action-button primary">Continue</button></form>{error && <p role="alert" className="game-error">{error}</p>}</section></main>;
  const busy = state.phase === "CREATING_GAME";
  return <main className="game-shell landing-shell"><section className="landing-table" aria-labelledby="gin-title"><header className="landing-header"><Link className="wordmark" href="/">Gin <span>Rummy</span></Link><div><Link href="/card-studio" className="quiet-link">Card Studio</Link>{state.phase === "READY_NAMED" && <><span>Playing as <b>{state.displayName}</b></span><Link href="/settings" className="quiet-link">Settings</Link></>}</div></header><div className="landing-content"><div className="landing-intro"><p className="eyebrow">A quiet game for two</p><h1 id="gin-title">The cards are on the table.</h1><p>Play as a guest—no account needed. Choose a name once and we’ll remember it on this device.</p><button type="button" className="action-button primary create-button" onClick={() => void createGame()} disabled={busy}>{busy ? "Creating game…" : "Create a private game"}</button></div><div className="landing-divider" aria-hidden="true"><span>or</span></div><form className="join-form" onSubmit={openInvite}><h2>Join a private game</h2><p>Paste the invitation link or invite code your friend sent you.</p><label>Invitation link or code<input value={inviteLink} placeholder="Paste a link or invite code" aria-describedby="invite-help" onChange={(event) => setInviteLink(event.target.value)} disabled={busy} /></label><p id="invite-help" className="invite-help">Paste a link or 43-character invite code to enable Join game.</p><button className="action-button secondary" disabled={busy || !inviteLink.trim()}>Join game</button></form></div>{recent.length > 0 && <section className="recent-games" aria-labelledby="recent-title"><div><p className="eyebrow">On this device</p><h2 id="recent-title">Recent tables</h2></div>{recent.map((item) => <Link key={item.gameId} href={`/game/${item.gameId}`}><span className="recent-avatar">{item.opponent.slice(0, 1)}</span><span><b>{item.opponent}</b><small>Resume table</small></span><span aria-hidden="true">→</span></Link>)}</section>}{state.phase === "READY_UNNAMED" && <p className="table-note">We’ll ask for your name before you create or join a game, then remember it on this device.</p>}{error && <p role="alert" className="game-error">{error}</p>}</section></main>;
}
function inviteTokenFromLink(value: string): string | null { const trimmed = value.trim(); if (/^[A-Za-z0-9_-]{43}$/.test(trimmed)) return trimmed; try { const url = new URL(trimmed); const match = url.pathname.match(/^\/join\/([A-Za-z0-9_-]{43})$/); return match?.[1] ?? null; } catch { return null; } }
function message(cause: unknown) { if (!(cause instanceof Error)) return "Something went wrong. Please try again."; if (cause.message === "INVALID_DISPLAY_NAME") return "Enter a name between 1 and 40 characters."; if (cause.message === "PROFILE_NAME_REQUIRED") return "Enter your name before starting a game."; return "Something went wrong. Please try again."; }
